name: Create Shadow Release

on:
  workflow_dispatch:
  
jobs:
  duplicate:
    runs-on: ubuntu-latest

    steps:
      - name: Get assets from latest release
        run: |
          response=$(curl https://api.github.com/repos/rzc0d3r/ESET-KeyGen/releases/latest)
          assets_url=$(echo "$response" | jq -r ".assets_url")
          src_code_archive_url=$(echo "$response" | jq -r ".zipball_url")
          assets_json=$(curl "$assets_url")

          # Downloading builds and source code
          curl "$src_code_archive_url"
          for url in $(echo "$assets_json" | jq -r '.[].browser_download_url'); do
            curl "$url"
          done
      - name: Creating shadow release
        run: |
          owner="shadowcopyrz"
          repo="ESET-KGEN-COPY"
          tag_name=$(echo "$response" | jq -r ".tag_name")
          release_name=$(echo "$response" | jq -r ".name")
          
          curl -X POST "https://api.github.com/repos/$owner/$repo/releases" \
            -H "Authorization: token ${{ secrets.PRJ_COPY }}" \
            -d '{
              "tag_name": "$tag_name",
              "name": "$release_name",
              "body": "",
              "draft": false,
              "prerelease": false
            }'
