name: Create Shadow Release

on:
  workflow_dispatch:
  
jobs:
  duplicate:
    runs-on: ubuntu-latest

    steps:
      - name: Get assets from latest release
        id: get_latest_release
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/rzc0d3r/ESET-KeyGen/releases/latest)
          assets_url=$(echo "$response" | jq -r ".assets_url")
          src_code_archive_url=$(echo "$response" | jq -r ".zipball_url")
          assets_json=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" "$assets_url")
          echo "$assets_json" ; "$src_code_archive_url"
          
