name: Test the project and update the test-date

on:
  schedule:
    - cron: '0 */12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: 'Generate key and update the test time'
        run: |
          ACCOUNT=0
          KEY=1
          EMAIL_API=guerrillamail
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git clone --depth 1 https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          sudo apt update
          sudo apt install python3-pip
          sudo pip install -r requirements.txt
          echo "Test results:" >> $GITHUB_STEP_SUMMARY
          if [[ ${ACCOUNT} != 0 ]]
          then
          for ((attempt=1;attempt<=${ACCOUNT};++attempt))
          do
          python3 main.py --chrome --account --email-api ${EMAIL_API} --skip-update-check --no-logo --disable-progress-bar
          done
          echo -e "\nAccounts generated:" >> $GITHUB_STEP_SUMMARY
          cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${KEY} != 0 ]]
          then
          for ((attempt=1;attempt<=${KEY};++attempt))
          do
          python3 main.py --chrome --key --email-api ${EMAIL_API} --skip-update-check --no-logo --disable-progress-bar
          done
          fi
          cd ${{ github.workspace }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ github.workspace }}
